FROM mcr.microsoft.com/devcontainers/typescript-node:16-bullseye

# RUN su vscode -c "npm install -g @angular/cli"
RUN npm install -g @angular/cli
# RUN git config --global oh-my-zsh.hide-dirty 1
# RUN git config --global oh-my-zsh.hide-info 1
